import {acceleration,advance} from './physics.js';
const el=id=>document.getElementById(id);
let state,t=0,running=false,last=0;
function values(){return {mass:+el('mass').value,force:+el('force').value,mu:+el('mu').value,v:+el('v0').value,x:0};}
function labels(){for(const [id,unit] of [['mass',' kg'],['force',' N'],['mu',''],['v0',' m/s']])el(id+'Out').textContent=(id==='mu'?(+el(id).value).toFixed(2):el(id).value)+unit;}
function arrow(id,label,force,y,color){const node=el(id);const labelNode=el(label);if(Math.abs(force)<.01){node.setAttribute('d','');labelNode.textContent='';return;}
 const end=320+Math.sign(force)*(20+Math.min(Math.abs(force)*5,200));node.setAttribute('d',`M320 ${y} H${end}`);labelNode.setAttribute('x',(320+end)/2);labelNode.setAttribute('y',y-12);labelNode.textContent=`${color} ${Math.abs(force).toFixed(1)} N`;}
function draw(){const f=acceleration(state);el('pos').textContent=state.x.toFixed(2)+' m';el('velocity').textContent=state.v.toFixed(2)+' m/s';el('accel').textContent=f.a.toFixed(2)+' m/s²';el('netText').textContent=`Gaya neto ${f.net.toFixed(2)} N · ${Math.abs(state.v)<.001?'diam saat ini':state.v>0?'bergerak ke kanan':'bergerak ke kiri'}`;el('timeText').textContent=`Waktu ${t.toFixed(2)} s`;el('massLabel').textContent=state.mass+' kg';arrow('forceArrow','forceLabel',state.force,90,'Dorong');arrow('frictionArrow','frictionLabel',f.friction,130,'Gesek');
 const start=Math.floor(state.x-4),end=Math.ceil(state.x+4);let marks='';for(let i=start;i<=end;i++){const px=320+(i-state.x)*80;if(px>=0&&px<=640)marks+=`<path d="M${px} 220V230" stroke="#61795e"/><text x="${px}" y="254" text-anchor="middle" font-size="13" fill="#50685b">${i} m</text>`;}el('ruler').innerHTML=marks;
}
function lock(){for(const id of ['mass','mu','v0'])el(id).disabled=running;el('run').textContent=running?'Jeda':t>=15?'Selesai':'Jalankan';el('run').disabled=t>=15;}
function reset(){running=false;t=0;state=values();labels();lock();draw();el('simStatus').textContent='Model siap. Pengaturan diterapkan; waktu kembali ke nol.';}
el('run').addEventListener('click',()=>{running=!running;last=0;lock();el('simStatus').textContent=running?'Model berjalan. Anda dapat mengubah atau melepas gaya dorong.':'Model dijeda. Jalankan lagi atau reset untuk percobaan baru.';});el('reset').addEventListener('click',reset);el('release').addEventListener('click',()=>{el('force').value=0;state.force=0;labels();draw();el('simStatus').textContent='Dorongan dilepas. Amati gerak dan gaya gesek.';});
for(const id of ['mass','mu','v0'])el(id).addEventListener('input',()=>reset());el('force').addEventListener('input',()=>{state.force=+el('force').value;labels();draw();});
const presets={inertia:{mass:2,force:0,mu:0,v0:2},friction:{mass:2,force:0,mu:.15,v0:2},push:{mass:2,force:8,mu:0,v0:0}};
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{for(const [id,val]of Object.entries(presets[b.dataset.preset]))el(id).value=val;reset();}));
function animate(now){if(running){const duration=last?Math.min((now-last)/1000,.05):0;let remaining=Math.min(duration,15-t);while(remaining>1e-8){const dt=Math.min(remaining,.005);state=advance(state,dt);t+=dt;remaining-=dt;}if(t>=15-1e-8){t=15;running=false;lock();el('simStatus').textContent='Percobaan 15 sekon selesai. Reset untuk mencoba keadaan lain.';}draw();}last=now;requestAnimationFrame(animate);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){running=false;lock();el('simStatus').textContent='Model dijeda ketika tab tidak aktif.';}});reset();requestAnimationFrame(animate);
const questions=[
 {q:'Benda bergerak lurus dengan kecepatan tetap. Apa yang dapat disimpulkan tentang gaya netonya?',options:['Gaya neto nol.','Gaya neto selalu searah gerak.','Tidak ada gaya apa pun yang bekerja.'],answer:0,why:'Gaya neto nol berarti percepatan nol. Beberapa gaya dapat tetap bekerja dan saling menyeimbangkan.'},
 {q:'Gaya neto 8 N bekerja pada benda bermassa 2 kg. Berapa percepatannya?',options:['16 m/s².','4 m/s².','0,25 m/s².'],answer:1,why:'Menurut ΣF = ma, percepatan 8 N ÷ 2 kg = 4 m/s².'},
 {q:'Benda bergerak ke kanan, tetapi gaya netonya ke kiri. Apa yang terjadi pada awalnya?',options:['Langsung bergerak ke kiri.','Kelajuannya bertambah ke kanan.','Geraknya ke kanan melambat.'],answer:2,why:'Percepatan ke kiri mengurangi kecepatan yang semula ke kanan. Benda dapat berbalik setelah kecepatannya mencapai nol jika gaya neto ke kiri tetap bekerja.'},
 {q:'Buku diam di meja. Manakah pasangan aksi–reaksi terhadap gaya meja pada buku?',options:['Gaya Bumi pada buku.','Gaya buku pada meja.','Gaya buku pada Bumi.'],answer:1,why:'Interaksi meja–buku menghasilkan gaya meja pada buku dan gaya buku pada meja. Keduanya bekerja pada benda berbeda.'},
 {q:'Setelah tangan dilepas, buku melambat di meja kasar. Penjelasan mana yang paling tepat?',options:['Gaya gesek menimbulkan percepatan berlawanan arah dengan gerak.','Buku kehabisan gaya yang tersimpan.','Massa buku terus bertambah.'],answer:0,why:'Gaya dorong tangan sudah tidak bekerja. Gesekan memberikan gaya neto yang memperlambat gerak buku.'}
];
const form=el('quiz');questions.forEach((item,i)=>{const field=document.createElement('fieldset');field.className='quiz-item';field.style.borderLeft=field.style.borderRight=field.style.borderTop='0';const legend=document.createElement('legend');legend.textContent=`${i+1}. ${item.q}`;field.append(legend);const opts=document.createElement('div');opts.className='quiz-options';item.options.forEach((text,j)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=j;label.append(input,document.createTextNode(text));opts.append(label);});field.append(opts);const fb=document.createElement('p');fb.id='feedback'+i;fb.className='feedback';fb.setAttribute('aria-live','polite');field.append(fb);form.append(field);});
form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('change',()=>{el('quizScore').textContent='Jawaban diubah. Periksa kembali untuk memperbarui hasil.';questions.forEach((q,i)=>{el('feedback'+i).textContent='';});});
el('checkQuiz').addEventListener('click',()=>{let score=0,answered=0;questions.forEach((q,i)=>{const selected=form.querySelector(`input[name="q${i}"]:checked`),fb=el('feedback'+i);if(!selected){fb.textContent='Pilih satu jawaban dahulu.';fb.className='feedback wrong';return;}answered++;const correct=+selected.value===q.answer;if(correct)score++;fb.textContent=(correct?'Tepat. ':'Belum tepat. ')+q.why;fb.className='feedback '+(correct?'correct':'wrong');});el('quizScore').textContent=`${score} dari ${questions.length} jawaban tepat · ${answered} soal dijawab. Tinjau alasan pada setiap soal.`;});
el('resetQuiz').addEventListener('click',()=>{form.reset();questions.forEach((q,i)=>el('feedback'+i).textContent='');el('quizScore').textContent='Latihan diulang.';});
const noteIds=['prediction','evidence','reflection'],key='inkuirilab-ipa-gaya-v1';let available=true;
try{const notes=JSON.parse(localStorage.getItem(key)||'{}');noteIds.forEach(id=>el(id).value=typeof notes[id]==='string'?notes[id]:'');}catch{available=false;el('notesStatus').textContent='Penyimpanan lokal tidak tersedia. Unduh catatan sebelum menutup halaman.';}
noteIds.forEach(id=>el(id).addEventListener('input',()=>{if(available)try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(noteIds.map(id=>[id,el(id).value]))));}catch{available=false;el('notesStatus').textContent='Catatan belum tersimpan otomatis. Gunakan Unduh catatan.';}}));
el('download').addEventListener('click',()=>{const text='CATATAN GAYA DAN GERAK\nKonsep Dasar IPA · PGMI\n\n'+noteIds.map((id,i)=>['Dugaan awal','Hasil pengamatan','Penjelasan akhir'][i]+'\n'+el(id).value).join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Catatan_Gaya_dan_Gerak.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
el('clearNotes').addEventListener('click',()=>{if(!confirm('Hapus seluruh catatan refleksi pada halaman ini?'))return;noteIds.forEach(id=>el(id).value='');try{localStorage.removeItem(key);}catch{}el('notesStatus').textContent='Catatan refleksi telah dihapus.';});
